
Meta:
  file: 'cnn_196'


Model:
  NeuralNet:
    ensemble: [
                'FBL_L1', 'FBL_L2', 'FBL_Sc', 'FBL_LDA', 'FBL_LDA_L1', 
                'FBLCR_L1', 'FBLCR_L2', 'FBLCR_Sc', 'FBLCR_LDA', 'FBLCR_LDA_L1',
                'FBL_delay_L1', 'FBL_delay_L2', 'FBL_delay_Sc', 'FBL_delay_LDA',
                
                'C500_[1_15]_LR', 'C500_[1_15]_LDA', 
                'C500_[7_30]_LR', 'C500_[7_30]_LDA',
                'C500_[20_35]_LR', 'C500_[20_35]_LDA',
                'C500_[70_150]_LR', 'C500_[70_150]_LDA',
                'C250_[35]_LR', 'C250_[35]_LDA',
                'C500_[35]_LR', 'C500_[35]_LDA',
                'ERPDist', 'ERPDist_LDA',
                'CAll_LR',
                
                'CovsRafal_35Hz_256','CovsRafal_35Hz_500',
                
                'CNN_1D_FB30',
                'CNN_2D_FB30', 
                'CNN_1D_FB7-30',
                'CNN_1D_FB5',
                
                'CNN_2D_FB30_shorterDelay',
                'CNN_1D_FB30_shorterDelay',
                
                'RNN_FB_delay4000',
                ]
    training_params:
      optim: 'adam'
      lr: 0.001
    
    delay: 1500
    skip: 100
    partsTrain: 4
    partsTest: 4
    smallEpochs: 1
    majorEpochs: 2
    checkEveryEpochs: 1

    architecture:
      - 'Dropout':
            p: 0.5
      - 'Conv':
            nb_filters: 8
      - 'Activation':
            type: 'relu'
      - 'Flatten':
      - 'Dense':
            num_units: 196
      - 'Activation':
            type: 'relu'
      - 'Dropout':
            p: 0.7
      - 'Output':